# $FreeBSD: releng/10.1/sys/modules/if_bridge/Makefile 160730 2006-07-26 22:15:15Z thompsa $

.include <bsd.own.mk>

.PATH:	${.CURDIR}/../../net
KMOD=	if_vether
SRCS=	if_vether.c 

.include <bsd.kmod.mk>
